"""
Forensic Report Parser for EYE AI Forensic Assistant.

This module provides parsing functionality for HTML forensic reports generated
by ReportEngine. It extracts report blocks (text, table, image) from HTML files
and converts them to ReportBlock objects for import into ReportEngine.

"""

from typing import List, Dict, Any, Optional
from bs4 import BeautifulSoup
import base64
import os
import logging
from datetime import datetime
from pathlib import Path

from eye.models.report_blocks import (
    ReportBlock, TextBlock, TableBlock, ImageBlock, ChatBlock, TimelineBlock, HeatmapBlock, ChainOfCustodyBlock
)


class ForensicReportParser:
    """
    Parser for HTML forensic reports generated by ReportEngine.
    
    Extracts report blocks (text, table, image) from HTML files and
    converts them to ReportBlock objects for import into ReportEngine.
    
    """
    
    def __init__(self, case_directory: str):
        """
        Initialize parser with case directory for image extraction.
        
        Args:
            case_directory: Path to case directory for saving extracted images
            
        """
        self.case_directory = Path(case_directory)
        self.logger = logging.getLogger(__name__)
    
    def parse_report_file(self, file_path: str) -> Dict[str, Any]:
        """
        Parse a single HTML forensic report file.
        
        Args:
            file_path: Path to HTML report file
            
        Returns:
            Dictionary with keys:
            - timestamp: Report generation timestamp
            - blocks: List of extracted block dictionaries
            - metadata: Report metadata
            - parse_errors: List of parsing errors
            
        Raises:
            FileNotFoundError: If report file does not exist
            PermissionError: If permission denied reading file
            IOError: If error reading file
            
        """
        parse_errors = []
        blocks = []
        timestamp = None
        metadata = {}
        
        # Load HTML file with error handling
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                html_content = f.read()
        except FileNotFoundError:
            raise FileNotFoundError(f"Report file not found: {file_path}")
        except PermissionError:
            raise PermissionError(f"Permission denied reading file: {file_path}")
        except Exception as e:
            raise IOError(f"Error reading file {file_path}: {str(e)}")
        
        # Parse HTML with BeautifulSoup4
        try:
            soup = BeautifulSoup(html_content, 'html.parser')
        except Exception as e:
            self.logger.error(f"Error parsing HTML from {file_path}: {e}")
            parse_errors.append(f"HTML parsing error: {str(e)}")
            # Return partial data even if parsing fails
            return {
                "timestamp": timestamp,
                "blocks": blocks,
                "metadata": metadata,
                "parse_errors": parse_errors
            }
        
        # Extract report metadata from .report-meta element
        try:
            meta_element = soup.find(class_='report-meta')
            if meta_element:
                # Extract timestamp from "Generated: YYYY-MM-DD HH:MM:SS" format
                meta_text = meta_element.get_text(strip=True)
                if "Generated:" in meta_text:
                    timestamp_str = meta_text.replace("Generated:", "").strip()
                    try:
                        # Parse timestamp
                        timestamp = datetime.strptime(timestamp_str, '%Y-%m-%d %H:%M:%S').isoformat()
                    except ValueError:
                        self.logger.warning(f"Could not parse timestamp: {timestamp_str}")
                        timestamp = datetime.now().isoformat()
                metadata["generated"] = meta_text
            else:
                self.logger.warning(f"No .report-meta element found in {file_path}")
                timestamp = datetime.now().isoformat()
        except Exception as e:
            self.logger.warning(f"Error extracting metadata: {e}")
            timestamp = datetime.now().isoformat()
        
        # Find all <section class="report-block"> elements
        try:
            sections = soup.find_all('section', class_='report-block')
            self.logger.info(f"Found {len(sections)} report blocks in {file_path}")
        except Exception as e:
            self.logger.error(f"Error finding report blocks: {e}")
            parse_errors.append(f"Error finding report blocks: {str(e)}")
            sections = []
        
        # Extract each block
        for section in sections:
            try:
                # Extract block ID from id attribute
                block_id = section.get('id', '')
                if not block_id:
                    self.logger.warning("Found report block without id attribute, skipping")
                    parse_errors.append("Block without id attribute")
                    continue
                
                # Identify block type from class
                classes = section.get('class', [])
                
                block_data = None
                if 'text-block' in classes:
                    block_data = self._extract_text_block(section)
                elif 'table-block' in classes:
                    block_data = self._extract_table_block(section)
                elif 'image-block' in classes:
                    block_data = self._extract_image_block(section)
                elif 'timeline-block' in classes:
                    block_data = self._extract_timeline_block(section)
                elif 'heatmap-block' in classes:
                    block_data = self._extract_heatmap_block(section)
                elif 'chat-block' in classes:
                    block_data = self._extract_chat_block(section)
                elif 'chart-block' in classes:
                    block_data = self._extract_chart_block(section)
                else:
                    self.logger.warning(f"Unknown block type for block {block_id}: {classes}")
                    parse_errors.append(f"Unknown block type: {classes}")
                    continue
                
                if block_data:
                    block_data['block_id'] = block_id
                    blocks.append(block_data)
                
            except Exception as e:
                self.logger.error(f"Error extracting block: {e}")
                parse_errors.append(f"Block extraction error: {str(e)}")
                # Continue processing remaining blocks
                continue
        
        return {
            "timestamp": timestamp,
            "blocks": blocks,
            "metadata": metadata,
            "parse_errors": parse_errors
        }
    
    def parse_reports_directory(
        self, 
        directory_path: str,
        pattern: str = "forensic_report_*.html"
    ) -> List[Dict[str, Any]]:
        """
        Parse all forensic reports in a directory.
        
        Args:
            directory_path: Path to directory containing HTML reports
            pattern: Glob pattern for matching report files (default: "forensic_report_*.html")
            
        Returns:
            List of parsed report dictionaries
            
        """
        parsed_reports = []
        directory = Path(directory_path)
        
        if not directory.exists():
            self.logger.error(f"Directory not found: {directory_path}")
            return parsed_reports
        
        if not directory.is_dir():
            self.logger.error(f"Path is not a directory: {directory_path}")
            return parsed_reports
        
        # Find all matching files
        matching_files = list(directory.glob(pattern))
        self.logger.info(f"Found {len(matching_files)} matching files in {directory_path}")
        
        # Parse each file
        for file_path in matching_files:
            try:
                self.logger.info(f"Parsing report: {file_path}")
                parsed_data = self.parse_report_file(str(file_path))
                parsed_data['source_file'] = str(file_path)
                parsed_reports.append(parsed_data)
            except Exception as e:
                self.logger.error(f"Error parsing {file_path}: {e}")
                # Continue processing remaining files
                continue
        
        return parsed_reports
    
    def convert_to_report_blocks(
        self, 
        parsed_data: Dict[str, Any]
    ) -> List[ReportBlock]:
        """
        Convert parsed dictionary data to ReportBlock objects.
        
        Args:
            parsed_data: Dictionary from parse_report_file()
            
        Returns:
            List of ReportBlock objects
            
        Raises:
            ValueError: If block data is invalid or missing required fields
            
        """
        report_blocks = []
        
        blocks_data = parsed_data.get('blocks', [])
        timestamp = parsed_data.get('timestamp')
        
        for block_dict in blocks_data:
            try:
                block_type = block_dict.get('block_type')
                block_id = block_dict.get('block_id')
                
                if not block_type:
                    self.logger.warning(f"Block missing block_type, skipping")
                    continue
                
                if not block_id:
                    self.logger.warning(f"Block missing block_id, skipping")
                    continue
                
                # Create metadata with timestamp
                metadata = {
                    "timestamp": timestamp or datetime.now().isoformat(),
                    "parsed_from_html": True
                }
                
                # Convert to appropriate ReportBlock subclass
                if block_type == 'text':
                    if 'title' not in block_dict or 'markdown_content' not in block_dict:
                        raise ValueError(f"TextBlock missing required fields: {block_dict.keys()}")
                    
                    block = TextBlock(
                        block_id=block_id,
                        title=block_dict['title'],
                        markdown_content=block_dict['markdown_content'],
                        metadata=metadata
                    )
                    report_blocks.append(block)
                    
                elif block_type == 'table':
                    if 'columns' not in block_dict or 'rows' not in block_dict:
                        raise ValueError(f"TableBlock missing required fields: {block_dict.keys()}")
                    
                    block = TableBlock(
                        block_id=block_id,
                        caption=block_dict.get('caption', ''),
                        columns=block_dict['columns'],
                        rows=block_dict['rows'],
                        sql_query=block_dict.get('sql_query', ''),
                        metadata=metadata
                    )
                    report_blocks.append(block)
                    
                elif block_type == 'image':
                    if 'image_path' not in block_dict:
                        raise ValueError(f"ImageBlock missing required field 'image_path': {block_dict.keys()}")
                    
                    block = ImageBlock(
                        block_id=block_id,
                        image_path=block_dict['image_path'],
                        caption=block_dict.get('caption', ''),
                        metadata=metadata
                    )
                    report_blocks.append(block)
                
                elif block_type == 'timeline':
                    block = TimelineBlock(
                        block_id=block_id,
                        title=block_dict.get('title', ''),
                        events=block_dict.get('events', []),
                        metadata=metadata
                    )
                    report_blocks.append(block)
                    
                elif block_type == 'heatmap':
                    block = HeatmapBlock(
                        block_id=block_id,
                        title=block_dict.get('title', ''),
                        x_labels=block_dict.get('x_labels', []),
                        y_labels=block_dict.get('y_labels', []),
                        intensity_values=block_dict.get('intensity_values', []),
                        metadata=metadata
                    )
                    report_blocks.append(block)
                    
                elif block_type == 'chat':
                    block = ChatBlock(
                        block_id=block_id,
                        messages=block_dict.get('messages', []),
                        metadata=metadata
                    )
                    report_blocks.append(block)
                    
                else:
                    self.logger.warning(f"Unknown block type '{block_type}', skipping")
                    continue
                    
            except ValueError as e:
                self.logger.error(f"Invalid block data: {e}")
                raise
            except Exception as e:
                self.logger.error(f"Error converting block to ReportBlock: {e}")
                continue
        
        return report_blocks
    
    def _extract_timeline_block(self, section: BeautifulSoup) -> Dict[str, Any]:
        """Extract data from timeline-block section."""
        try:
            title_elem = section.find('h2')
            title = title_elem.get_text(strip=True) if title_elem else "Timeline"
            
            events = []
            event_elems = section.find_all('div', class_='timeline-event')
            for ev in event_elems:
                label_elem = ev.find('span', class_='timeline-event-label')
                time_elem = ev.find('span', class_='timeline-event-time')
                desc_elem = ev.find('div', class_='timeline-event-description')
                cat_elem = ev.find('div', class_='timeline-event-category')
                
                events.append({
                    "label": label_elem.get_text(strip=True) if label_elem else "Event",
                    "timestamp": time_elem.get_text(strip=True) if time_elem else "",
                    "description": desc_elem.get_text(strip=True) if desc_elem else "",
                    "category": cat_elem.get_text(strip=True) if cat_elem else "General"
                })
            
            return {
                "block_type": "timeline",
                "title": title,
                "events": events
            }
        except Exception as e:
            self.logger.error(f"Error extracting timeline block: {e}")
            return {"block_type": "timeline", "title": "Error", "events": []}

    def _extract_heatmap_block(self, section: BeautifulSoup) -> Dict[str, Any]:
        """Extract data from heatmap-block section."""
        try:
            title_elem = section.find('h2')
            title = title_elem.get_text(strip=True) if title_elem else "Heatmap"
            
            # This is a bit complex as the grid is rendered as flex divs
            # We'll do a basic extraction of labels and values
            x_labels = []
            header = section.find('div', style=lambda s: s and 'display: flex' in s)
            if header:
                x_labels = [div.get_text(strip=True) for div in header.find_all('div') if div.get_text(strip=True)]
                
            y_labels = []
            intensity_values = []
            rows = section.find_all('div', style=lambda s: s and 'display: flex' in s)[1:] # Skip header
            for row in rows:
                divs = row.find_all('div')
                if not divs: continue
                y_labels.append(divs[0].get_text(strip=True))
                intensity_values.append([float(div.get_text(strip=True) or 0) for div in divs[1:]])
                
            return {
                "block_type": "heatmap",
                "title": title,
                "x_labels": x_labels,
                "y_labels": y_labels,
                "intensity_values": intensity_values
            }
        except Exception as e:
            self.logger.error(f"Error extracting heatmap block: {e}")
            return {"block_type": "heatmap", "title": "Error", "x_labels": [], "y_labels": [], "intensity_values": []}

    def _extract_chat_block(self, section: BeautifulSoup) -> Dict[str, Any]:
        """Extract data from chat-block section."""
        try:
            messages = []
            msg_elems = section.find_all('div', class_='chat-message')
            for msg in msg_elems:
                role = "assistant" if 'ai-message' in msg.get('class', []) else "user"
                content = msg.decode_contents().replace('<br>', '\n')
                messages.append({"role": role, "content": content})
            
            return {
                "block_type": "chat",
                "messages": messages
            }
        except Exception as e:
            self.logger.error(f"Error extracting chat block: {e}")
            return {"block_type": "chat", "messages": []}

    def _extract_chart_block(self, section: BeautifulSoup) -> Dict[str, Any]:
        """Extract data from chart-block section by parsing embedded JSON config."""
        try:
            script_tag = section.find('script')
            if not script_tag:
                return {"block_type": "chart", "title": "Chart", "labels": [], "datasets": [], "chart_type": "bar"}
            
            # Extract JSON from script: "new Chart(..., { ... });"
            script_content = script_tag.string
            start = script_content.find('{')
            end = script_content.rfind('}')
            if start == -1 or end == -1:
                return {"block_type": "chart", "title": "Chart", "labels": [], "datasets": [], "chart_type": "bar"}
                
            config_json = script_content[start:end+1]
            config = json.loads(config_json)
            
            return {
                "block_type": "chart",
                "chart_type": config.get("type", "bar"),
                "title": config.get("options", {}).get("plugins", {}).get("title", {}).get("text", "Chart"),
                "labels": config.get("data", {}).get("labels", []),
                "datasets": config.get("data", {}).get("datasets", [])
            }
        except Exception as e:
            self.logger.error(f"Error extracting chart block: {e}")
            return {"block_type": "chart", "title": "Error", "labels": [], "datasets": [], "chart_type": "bar"}

    def _extract_text_block(self, section: BeautifulSoup) -> Dict[str, Any]:
        """
        Extract data from text-block section.
        
        Args:
            section: BeautifulSoup element for text-block section
            
        Returns:
            Dictionary with extracted text block data
            
        """
        try:
            # Extract title from <h2> element
            title_elem = section.find('h2')
            # Use get_text() without strip to preserve whitespace exactly as rendered
            # This ensures round-trip fidelity for property-based tests
            title = title_elem.get_text() if title_elem else ""
            
            if not title:
                self.logger.warning("Text block missing title, using empty string")
            
            # Extract content from .text-content div
            content_elem = section.find('div', class_='text-content')
            if content_elem:
                # Get HTML content (already rendered from markdown)
                markdown_content = content_elem.decode_contents()
            else:
                self.logger.warning("Text block missing .text-content element")
                markdown_content = ""
            
            return {
                "block_type": "text",
                "title": title,
                "markdown_content": markdown_content
            }
            
        except Exception as e:
            self.logger.error(f"Error extracting text block: {e}")
            return {
                "block_type": "text",
                "title": "",
                "markdown_content": ""
            }
    
    def _extract_table_block(self, section: BeautifulSoup) -> Dict[str, Any]:
        """
        Extract data from table-block section.
        
        Args:
            section: BeautifulSoup element for table-block section
            
        Returns:
            Dictionary with extracted table block data
            
        """
        try:
            # Extract caption from .table-caption element
            caption_elem = section.find('p', class_='table-caption')
            # Use get_text() without strip to preserve whitespace, but normalize line endings
            # HTML normalizes \r to \n, so we do the same for round-trip fidelity
            caption = caption_elem.get_text().replace('\r\n', '\n').replace('\r', '\n') if caption_elem else ""
            
            if not caption:
                self.logger.warning("Table block missing caption, using empty string")
            
            # Extract table columns from <thead><th> elements
            columns = []
            thead = section.find('thead')
            if thead:
                th_elements = thead.find_all('th')
                columns = [th.get_text(strip=True) for th in th_elements]
            else:
                self.logger.warning("Table block missing <thead> element")
            
            if not columns:
                self.logger.warning("Table block has no columns")
            
            # Extract table rows from <tbody><tr><td> elements
            rows = []
            tbody = section.find('tbody')
            if tbody:
                tr_elements = tbody.find_all('tr')
                for tr in tr_elements:
                    td_elements = tr.find_all('td')
                    if len(td_elements) == len(columns):
                        row_dict = {
                            columns[i]: td.get_text(strip=True)
                            for i, td in enumerate(td_elements)
                        }
                        rows.append(row_dict)
                    else:
                        self.logger.warning(f"Row has {len(td_elements)} cells but table has {len(columns)} columns")
            else:
                self.logger.warning("Table block missing <tbody> element")
            
            if not rows:
                self.logger.warning("Table block has no rows")
            
            # Extract SQL query from <details class="sql-query"><pre><code>
            sql_query = ""
            details = section.find('details', class_='sql-query')
            if details:
                code_elem = details.find('code')
                if code_elem:
                    sql_query = code_elem.get_text(strip=True)
            
            return {
                "block_type": "table",
                "caption": caption,
                "columns": columns,
                "rows": rows,
                "sql_query": sql_query
            }
            
        except Exception as e:
            self.logger.error(f"Error extracting table block: {e}")
            return {
                "block_type": "table",
                "caption": "",
                "columns": [],
                "rows": [],
                "sql_query": ""
            }
    
    def _extract_image_block(self, section: BeautifulSoup) -> Dict[str, Any]:
        """
        Extract data from image-block section.
        
        Args:
            section: BeautifulSoup element for image-block section
            
        Returns:
            Dictionary with extracted image block data
            
        """
        try:
            # Extract image src from <img> element
            img_elem = section.find('img')
            if not img_elem:
                self.logger.error("Image block missing <img> element")
                return None
            
            img_src = img_elem.get('src', '')
            if not img_src:
                self.logger.error("Image block <img> missing src attribute")
                return None
            
            # Extract caption from <figcaption> element
            caption_elem = section.find('figcaption')
            caption = caption_elem.get_text(strip=True) if caption_elem else ""
            
            # Handle data URI (base64 encoded images)
            if img_src.startswith('data:'):
                try:
                    # Generate block_id for filename (will be replaced with actual block_id later)
                    block_id = section.get('id', 'unknown')
                    image_path = self._decode_base64_image(img_src, block_id)
                except Exception as e:
                    self.logger.error(f"Error decoding base64 image: {e}")
                    return None
            else:
                # Regular file path
                image_path = img_src
            
            return {
                "block_type": "image",
                "image_path": image_path,
                "caption": caption
            }
            
        except Exception as e:
            self.logger.error(f"Error extracting image block: {e}")
            return None
    
    def _decode_base64_image(
        self, 
        data_uri: str, 
        block_id: str
    ) -> str:
        """
        Decode base64 image data and save to case directory.
        
        Args:
            data_uri: Data URI with base64 encoded image
            block_id: Block ID for filename generation
            
        Returns:
            Path to saved image file
            
        Raises:
            ValueError: If data URI is invalid or base64 decode fails
            
        """
        try:
            # Parse data URI: data:image/png;base64,iVBORw0KG...
            if not data_uri.startswith('data:'):
                raise ValueError(f"Invalid data URI: does not start with 'data:'")
            
            # Split into mime type and data
            parts = data_uri.split(',', 1)
            if len(parts) != 2:
                raise ValueError(f"Invalid data URI format: missing comma separator")
            
            header, encoded_data = parts
            
            # Extract mime type and encoding
            # Format: data:image/png;base64
            mime_parts = header.split(';')
            if len(mime_parts) < 2 or mime_parts[1] != 'base64':
                raise ValueError(f"Invalid data URI: not base64 encoded")
            
            mime_type = mime_parts[0].replace('data:', '')
            
            # Determine file extension from mime type
            ext_map = {
                'image/png': '.png',
                'image/jpeg': '.jpg',
                'image/jpg': '.jpg',
                'image/gif': '.gif',
                'image/svg+xml': '.svg'
            }
            ext = ext_map.get(mime_type, '.png')
            
            # Decode base64 data
            try:
                image_data = base64.b64decode(encoded_data)
            except Exception as e:
                raise ValueError(f"Base64 decode failed: {str(e)}")
            
            # Create images directory in case directory
            images_dir = self.case_directory / "imported_images"
            images_dir.mkdir(parents=True, exist_ok=True)
            
            # Generate filename from block_id
            filename = f"{block_id}{ext}"
            image_path = images_dir / filename
            
            # Save image to file
            with open(image_path, 'wb') as f:
                f.write(image_data)
            
            self.logger.info(f"Saved base64 image to {image_path}")
            
            return str(image_path)
            
        except Exception as e:
            self.logger.error(f"Error decoding base64 image: {e}")
            raise ValueError(f"Failed to decode base64 image: {str(e)}")
